COMPONENT=TSyncAppC

PFLAGS += -I../Application/CRFtspApp/
CFLAGS += -DPERIOD=20000
#CFLAGS += -DTOSH_DATA_LENGTH=52

PFLAGS += -I../../tos/platforms/micaz/
CFLAGS +=-I../../tos/platforms/micaz/CC2420X

include $(MAKERULES)

