COMPONENT=TSyncAppC

PFLAGS += -I../Application/AvtspApp/
CFLAGS += -DPERIOD=20000
#CFLAGS += -DTOSH_DATA_LENGTH=40

#PFLAGS += -I../../tos/platforms/micaz/
#CFLAGS +=-I../../tos/platforms/micaz/CC2420X

include $(MAKERULES)

